# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 270)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 0, 51, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 381, 181))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt;\">💻</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#3f2e62;\">QR Encoder 1.0</span></p><p align=\"center\"><span style=\" font-size:18pt; color:#3f2e62;\"><br/></span></p><p><span style=\" font-size:18pt; color:#3f2e62;\"><br/></span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Hotkey list:"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p>Ctrl+S - Save to the base folder</p><p>Ctrl+Shift+S - Save As</p><p>Ctrl+O - Open a database file</p><p>Ctrl+G - Generate a QR Code, given enough sufficient data</p><p>Ctrl+Enter - Generate a QR Code from inside the input box</p><p>Ctrl+← - Move to the leftmost tab (Plaintext to QR)</p><p>Ctrl+→ - Move to the rightmost tab (Database item to QR)</p></body></html>"))
