# Form implementation generated from reading ui file 'QRViewer.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(480, 600))
        Dialog.setMaximumSize(QtCore.QSize(480, 600))
        self.imgDisplay = QtWidgets.QListWidget(Dialog)
        self.imgDisplay.setEnabled(True)
        self.imgDisplay.setGeometry(QtCore.QRect(0, 0, 480, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgDisplay.sizePolicy().hasHeightForWidth())
        self.imgDisplay.setSizePolicy(sizePolicy)
        self.imgDisplay.setMinimumSize(QtCore.QSize(480, 600))
        self.imgDisplay.setSizeIncrement(QtCore.QSize(0, 0))
        self.imgDisplay.setBaseSize(QtCore.QSize(0, 0))
        self.imgDisplay.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.imgDisplay.setIconSize(QtCore.QSize(100, 200))
        self.imgDisplay.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.imgDisplay.setViewMode(QtWidgets.QListView.ViewMode.IconMode)
        self.imgDisplay.setUniformItemSizes(False)
        self.imgDisplay.setObjectName("imgDisplay")
        self.imgDisplay.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
